2025-01-07 18:45:48,679 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\python\PyProjectsForStudy\homework\module12\tests_12_4.py", line 23, in test_run
    runner_2 = Runner(12345)
               ^^^^^^^^^^^^^
  File "C:\python\PyProjectsForStudy\homework\module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2025-01-07 18:45:48,682 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\python\PyProjectsForStudy\homework\module12\tests_12_4.py", line 13, in test_walk
    runner_1 = Runner('name', -5)
               ^^^^^^^^^^^^^^^^^^
  File "C:\python\PyProjectsForStudy\homework\module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
